### ISSUE TITLE
Keywords are incomplete

### ISSUE THREAD

**Issue by wilzbach** [storyscript/syntax#1]
![image](https://user-images.githubusercontent.com/4370550/55499697-ef0fcb80-5646-11e9-92ce-94c9696bf875.png)

Also note that `returns` isn't a keyword.

**Comment by stevepeak** [comment]
@wilzbach the keywords `true, false, null` are detected and marked as `null == support.constant` and `booleans == constant.other`. Python syntax highlighting has booleans marked as `constant.language`.

`and` was not correctly detected.

**Comment by adnrs96** [comment]
I think `returns` is a keyword now? Maybe it was introduced after you opened this issue @wilzbach 
I am adding two new keywords i.e. `throw` and `to`
